[package]
name = "bedrockrs_nbt"
version = "1.0.0"
edition = "2021"
authors = ["Ruben Adema", "theaddonn <theaddonn@gmail.com>"]
repository = "https://github.com/bedrock-crustaceans/bedrockrs-nbt"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
paste = "1.0"
thiserror = "1.0"
